name: CMake Build
run-name: ${{ github.actor }} is building OpenSees triggered by a ${{ github.event_name }} event
env:
  CMAKE_VERSION: 3.27.1
  BUILD_TYPE: Debug

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Ubuntu bundled build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install conan
      run: python3 -m pip install conan==1.60.0

    - name: Detect Conan Defaults
      run: |
        conan --version

    - name: Build
      run: |
        mkdir build
        cd build
        conan install .. --build missing
        cmake ..
        cmake --build . -j8

        #- name: Verification
        #  run: |
        #    cd ./EXAMPLES/verification/ && ../../build/OpenSeesTcl runVerificationSuite.tcl
    - name: Build OpenSeesPy
      run: |
        cd ./build
        cmake ..
        make -j 4
        make OpenSeesPy
        mkdir fake_folder
    - name: Rename OpenSeesPy
      run: |
        cd ./build
        mv lib/OpenSeesPy.so lib/opensees.so

# Simple sanity test
    - name: Verification OpenSeesPySP
      run: |
        cd ./build
        cd ../EXAMPLES/ExamplePython/
        export PYTHONPATH="../../build/lib/"
        python -c "import sys; print(sys.path)"
        python example_variable_analysis.py
#        # Simple MP sanity test
#        - name: Verification OpenSeesPyMP
#          run: |
#            mpiexec -np 2 python ../EXAMPLES/ExamplePython/example_mpi_paralleltruss_explicit.py


  build-windows:
        name: Windows build
        runs-on: [windows-latest]
        #runs-on: self-hosted
        steps:
        - name: Checkout Sources
          uses: actions/checkout@v2
        - name: Setup Python  
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"
        - name: Install conan
          run: python3 -m pip install conan==1.60.0
          
        - name: Setup Fortran
          uses: mckee107/setup-oneAPI@main
          id: setup-oneAPI
          with:
            compiler: intel
            version: 2023.2
        - name: Build
          shell: cmd
          run: |
            mkdir build
            cd build
            conan --version
            cmake --version
            conan config install -t dir ../.github/.conan
            conan install .. --build missing -pr:h=OPS_Win_Intel -pr:b=OPS_Win_Intel
            cmake .. 
            cmake --build . --target OpenSeesTcl -j8
          env:
            FC: ${{ steps.setup-fortran.outputs.fc }}
            CC: ${{ steps.setup-fortran.outputs.cc }}
            CMAKE_CXX_COMPILER: $CC
            CMAKE_Fortran_COMPILER: $FC
        
        
