name: CMake Build
run-name: ${{ github.actor }} is building OpenSees triggered by a ${{ github.event_name }} event
env:
  CMAKE_VERSION: 3.27.1
  BUILD_TYPE: Debug

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build-ubuntu:
    name: Ubuntu bundled build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install conan
      run: python3 -m pip install conan==1.60.0

    - name: Detect Conan Defaults
      run: |
        conan --version

    - name: Build
      run: |
        mkdir build
        cd build
        conan install .. --build missing
        cmake ..
        cmake --build . -j8

        #- name: Verification
        #  run: |
        #    cd ./EXAMPLES/verification/ && ../../build/OpenSeesTcl runVerificationSuite.tcl
    - name: Build OpenSeesPy
      run: |
        cd ./build
        cmake ..
        make -j 4
        make OpenSeesPy
        mkdir fake_folder
    - name: Rename OpenSeesPy
      run: |
        cd ./build
        mv lib/OpenSeesPy.so lib/opensees.so

# Simple sanity test
    - name: Verification OpenSeesPySP
      run: |
        cd ./build
        cd ../EXAMPLES/ExamplePython/
        export PYTHONPATH="../../build/lib/"
        python -c "import sys; print(sys.path)"
        python example_variable_analysis.py
#        # Simple MP sanity test
#        - name: Verification OpenSeesPyMP
#          run: |
#            mpiexec -np 2 python ../EXAMPLES/ExamplePython/example_mpi_paralleltruss_explicit.py


  build-windows:
        name: Windows build
        runs-on: [windows-latest]
        steps:
        - name: Checkout Sources
          uses: actions/checkout@v2
          
        - name: Setup MSBuild
          uses: microsoft/setup-msbuild@v1
          
        - name: Setup Fortran
          uses: mckee107/setup-fortran@v1.1.1
          with:
            compiler: intel
            version: latest
            
        - name: Set Environment
          run: |
            ${{ env.FC }} --version
            ${{ env.CC }} --version
          env:
            FC: ${{ steps.setup-fortran.outputs.fc }}
            CC: ${{ steps.setup-fortran.outputs.cc }}
        
        - name: Build
          shell: cmd 
          run: |
            mkdir build
            cd build
            call "%ONEAPI_ROOT%\setvars.bat" --force
            cmake .. 
            cmake --build . --target OpenSeesTcl -j8


